# SFTP credentials
HOST = "sftp.barra.com"
PORT = 22
USERNAME = "udkkosfh"
PASSWORD = ".j(+Sa/hfs/E+4tGC_Y6"

BARRA_RAW_DATA_DIR = r'C:\Python\data\factor_data\raw'
BARRA_PROCESSED_DATA_DIR = r'C:\Python\data\factor_data\processed'
BARRA_ATTRIB_DATA_DIR = r'C:\Python\data\factor_data\attrib'
BARRA_MASTER_DIR = r'C:\Python\data\factor_data'
BARRA_TEMP_HELPER_DIR = r'C:\Python\data\factor_data\temp'
BARRA_BBG_MAPPING_FILE_NAME = 'barrid_to_bbg.pkl'

SERVER_DAILY_PATH_PREFIX = "/apacefmtr/"
SERVER_HIST_PATH_PREFIX = "/history/apacefmtr/sm/daily/"

ATTRIB_HIST_PICKLE_NM = "historical_attrib.pkl"
FULL_ATTRIB_PICKLE_NM = "full_attrib.pkl"

DAILY_FILE_LIST = [
    "GMD_APACEFMTR_Market_Data_DATEPLACEHOLDER.zip",
    "GMD_APACEFMTRD_100_DATEPLACEHOLDER.zip",
    "GMD_ASIA_FIGI_ID_DATEPLACEHOLDER.zip"]

HIST_ASSET_DATA_STRUCTURE = {
    "pattern": r"GMD_APACEFMTR_100_D_(\d{4})(_\d+)?\.zip",
    "file_types": {
        "specific_return": r"APACEFMTR_100_Asset_DlySpecRet\.(\d{8})",
        "daily_price": r"APACEFMTR_Daily_Asset_Price\.(\d{8})",
        "fx_rate": r"APACEFMTR_Rates\.(\d{8})",
        "daily_volume": r"APACEFMTR_Market_Data\.(\d{8})"
    },
    "columns": {
        "specific_return": ["Barrid", "SpecificReturn", "DataDate"],
        "daily_price": ["Barrid", "Price", "Capt", "PriceSource", "Currency", "DlyReturn%", "DataDate"],
        "fx_rate": ["Currency", "USDxrate", "RFRate%", "DataDate"],
        "daily_volume": ["Barrid", "BidAskSpread", "ADBAS_30", "ADBAS_60", "ADBAS_90", "DailyVolume",
                         "ADTV_30", "ADTV_60", "ADTV_90", "ADPS", "CompositeVolume",
                         "ADTCV_30", "ADTCV_60", "ADTCV_90", "ADTCA_30", "IssuerMarketCap", "DataDate"]
    },
    "delimiter": "|"
    }

HIST_FACTOR_DATA_STRUCTURE = {
    "pattern": r"GMD_APACEFMTRD_100_D_(\d{4})(_\d+)?\.zip",
    "file_types": {
        "asset_data": r"APACEFMTRD_100_Asset_Data\.(\d{8})",
        "asset_exposure": r"APACEFMTRD_100_Asset_Exposure\.(\d{8})",
        "covariance": r"APACEFMTRD_100_Covariance\.(\d{8})"
    },
    "columns": {
        "asset_data": ["Barrid", "Yield%", "TotalRisk%", "SpecRisk%", "HistBeta", "PredBeta", "DataDate"],
        "asset_exposure": ["Barrid", "Factor", "Exposure", "DataDate"],
        "covariance": ["Factor1", "Factor2", "VarCovar", "DataDate"]
    },
    "delimiter": "|"
}

HIST_DATA_STRUCTURE_DICT = {
    'asset_data': HIST_ASSET_DATA_STRUCTURE,
    'factor_data': HIST_FACTOR_DATA_STRUCTURE
}

LATEST_DATA_DICT = {
            "pattern": r"GMD_APACEFMTRD_100_\d{6}\.zip",
            "file_types": {
                "asset_data": r"APACEFMTRD_100_Asset_Data\.(\d{8})",
                "asset_exposure": r"APACEFMTRD_100_Asset_Exposure\.(\d{8})",
                "specific_return": r"APACEFMTR_100_Asset_DlySpecRet\.(\d{8})",
                "daily_price": r"APACEFMTR_Daily_Asset_Price\.(\d{8})",
                "fx_rate": r"APACEFMTR_Rates\.(\d{8})",
                "factor_return": r"APACEFMTRD_100_DlyFacRet\.(\d{8})",
                "covariance": r"APACEFMTRD_100_Covariance\.(\d{8})"
            },
            "columns": {
                "asset_data": ["Barrid", "Yield%", "TotalRisk%", "SpecRisk%", "HistBeta", "PredBeta", "DataDate"],
                "asset_exposure": ["Barrid", "Factor", "Exposure", "DataDate"],
                "specific_return": ["Barrid", "SpecificReturn", "DataDate"],
                "daily_price": ["Barrid", "Price", "Capt", "PriceSource", "Currency", "DlyReturn%", "DataDate"],
                "fx_rate": ["Currency", "USDxrate", "RFRate%", "DataDate"],
                "factor_return": ["Factor", "DlyReturn", "DataDate"],
                "covariance": ["Factor1", "Factor2", "VarCovar", "DataDate"]
            },
            "delimiter": "|"
        }

# Region Factor Mapping

FACTOR_MAPPING = [{'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_ANLYSTSN',
  'FactorDisplayName': 'ASP Analysts Sentiment',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '1',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_BETA',
  'FactorDisplayName': 'ASP Beta',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '2',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_CARBONEFF',
  'FactorDisplayName': 'ASP Carbon Efficiency',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '3',
  'StartDate': '20201231',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_DIVYILD',
  'FactorDisplayName': 'ASP Dividend Yield',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '4',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_EARNQLTY',
  'FactorDisplayName': 'ASP Earnings Quality',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '5',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_EARNVAR',
  'FactorDisplayName': 'ASP Earnings Variability',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '6',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_EARNYILD',
  'FactorDisplayName': 'ASP Earnings Yield',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '7',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_ESG',
  'FactorDisplayName': 'ASP ESG',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '8',
  'StartDate': '20070131',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_EXASPEXP',
  'FactorDisplayName': 'ASP Ex-Asia Pacific Economic Exposure',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '9',
  'StartDate': '20021129',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_GROWTH',
  'FactorDisplayName': 'ASP Growth',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '10',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_INDMOM',
  'FactorDisplayName': 'ASP Industry Momentum',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '11',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_INVSQLTY',
  'FactorDisplayName': 'ASP Investment Quality',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '12',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPBETA',
  'FactorDisplayName': 'ASP (JPN) Beta',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '13',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPCARBONEFF',
  'FactorDisplayName': 'ASP (JPN) Carbon Efficiency',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '14',
  'StartDate': '20201231',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPDIVYILD',
  'FactorDisplayName': 'ASP (JPN) Dividend Yield',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '15',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPEARNYILD',
  'FactorDisplayName': 'ASP (JPN) Earnings Yield',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '16',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPESG',
  'FactorDisplayName': 'ASP (JPN) ESG',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '17',
  'StartDate': '20070131',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPGROWTH',
  'FactorDisplayName': 'ASP (JPN) Growth',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '18',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPLEVERAGE',
  'FactorDisplayName': 'ASP (JPN) Leverage',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '19',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPLIQUIDTY',
  'FactorDisplayName': 'ASP (JPN) Liquidity',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '20',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPMIDCAP',
  'FactorDisplayName': 'ASP (JPN) Mid Capitalization',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '21',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPMOMENTUM',
  'FactorDisplayName': 'ASP (JPN) Momentum',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '22',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPRESVOL',
  'FactorDisplayName': 'ASP (JPN) Residual Volatility',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '23',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPSIZE',
  'FactorDisplayName': 'ASP (JPN) Size',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '24',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPVALUE',
  'FactorDisplayName': 'ASP (JPN) Value',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '25',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_LEVERAGE',
  'FactorDisplayName': 'ASP Leverage',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '26',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_LIQUIDTY',
  'FactorDisplayName': 'ASP Liquidity',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '27',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_LTREVRSL',
  'FactorDisplayName': 'ASP Long-Term Reversal',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '28',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_MIDCAP',
  'FactorDisplayName': 'ASP Mid Capitalization',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '29',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_MLFAC',
  'FactorDisplayName': 'ASP ML Factor',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '30',
  'StartDate': '20000731',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_MOMENTUM',
  'FactorDisplayName': 'ASP Momentum',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '31',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_PROFIT',
  'FactorDisplayName': 'ASP Profitability',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '32',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_RESVOL',
  'FactorDisplayName': 'ASP Residual Volatility',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '33',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_SEASON',
  'FactorDisplayName': 'ASP Seasonality',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '34',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_STREVRSL',
  'FactorDisplayName': 'ASP Short-Term Reversal',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '35',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_SIZE',
  'FactorDisplayName': 'ASP Size',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '36',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_CROWD',
  'FactorDisplayName': 'ASP Stock Crowding',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '37',
  'StartDate': '19950630',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_VALUE',
  'FactorDisplayName': 'ASP Value',
  'FactorGroup': '1-Risk Indices',
  'FactorNum': '38',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPAIRMARINE',
  'FactorDisplayName': 'ASP (JPN) Airlines and Marine',
  'FactorGroup': '2-Industries',
  'FactorNum': '39',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_AIRMARINE',
  'FactorDisplayName': 'ASP Airlines and Marine',
  'FactorGroup': '2-Industries',
  'FactorNum': '40',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPAUTOCOMP',
  'FactorDisplayName': 'ASP (JPN) Automobiles and Components',
  'FactorGroup': '2-Industries',
  'FactorNum': '41',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_AUTOCOMP',
  'FactorDisplayName': 'ASP Automobiles and Components',
  'FactorGroup': '2-Industries',
  'FactorNum': '42',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPBANKS',
  'FactorDisplayName': 'ASP (JPN) Banks',
  'FactorGroup': '2-Industries',
  'FactorNum': '43',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_BANKS',
  'FactorDisplayName': 'ASP Banks',
  'FactorGroup': '2-Industries',
  'FactorNum': '44',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_BUILD',
  'FactorDisplayName': 'ASP Building Products and Construction',
  'FactorGroup': '2-Industries',
  'FactorNum': '45',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPBUILD',
  'FactorDisplayName': 'ASP (JPN) Building Products and Construction',
  'FactorGroup': '2-Industries',
  'FactorNum': '46',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_CAPGOODS',
  'FactorDisplayName': 'ASP Capital Goods ex Building and Machinery',
  'FactorGroup': '2-Industries',
  'FactorNum': '47',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPCAPGOODS',
  'FactorDisplayName': 'ASP (JPN) Capital Goods ex Building and Machinery',
  'FactorGroup': '2-Industries',
  'FactorNum': '48',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPCHEMICAL',
  'FactorDisplayName': 'ASP (JPN) Chemicals',
  'FactorGroup': '2-Industries',
  'FactorNum': '49',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_CHEMICAL',
  'FactorDisplayName': 'ASP Chemicals',
  'FactorGroup': '2-Industries',
  'FactorNum': '50',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_COMTRA',
  'FactorDisplayName': 'ASP Commercial Services and Transportation',
  'FactorGroup': '2-Industries',
  'FactorNum': '51',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPCOMPUTER',
  'FactorDisplayName': 'ASP (JPN) Computers and Peripherals',
  'FactorGroup': '2-Industries',
  'FactorNum': '52',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_COMPUTER',
  'FactorDisplayName': 'ASP Computers and Peripherals',
  'FactorGroup': '2-Industries',
  'FactorNum': '53',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPCONSTR',
  'FactorDisplayName': 'ASP (JPN) Construction Materials and Packaging',
  'FactorGroup': '2-Industries',
  'FactorNum': '54',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_CONSTR',
  'FactorDisplayName': 'ASP Construction Materials and Packaging',
  'FactorGroup': '2-Industries',
  'FactorNum': '55',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPCONSDUR',
  'FactorDisplayName': 'ASP (JPN) Consumer Durables and Apparel',
  'FactorGroup': '2-Industries',
  'FactorNum': '56',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_CONSDUR',
  'FactorDisplayName': 'ASP Consumer Durables and Apparel',
  'FactorGroup': '2-Industries',
  'FactorNum': '57',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPHOTEL',
  'FactorDisplayName': 'ASP (JPN) Consumer Services',
  'FactorGroup': '2-Industries',
  'FactorNum': '58',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_HOTEL',
  'FactorDisplayName': 'ASP Consumer Services',
  'FactorGroup': '2-Industries',
  'FactorNum': '59',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_CONSTAP',
  'FactorDisplayName': 'ASP Consumer Staples',
  'FactorGroup': '2-Industries',
  'FactorNum': '60',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPCONSTAP',
  'FactorDisplayName': 'ASP (JPN) Consumer Staples',
  'FactorGroup': '2-Industries',
  'FactorNum': '61',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_DIVFINAN',
  'FactorDisplayName': 'ASP Diversified Financials',
  'FactorGroup': '2-Industries',
  'FactorNum': '62',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPDIVFINAN',
  'FactorDisplayName': 'ASP (JPN) Diversified Financials and Insurance',
  'FactorGroup': '2-Industries',
  'FactorNum': '63',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_HARDWARE',
  'FactorDisplayName': 'ASP Electronic Equipment and Components',
  'FactorGroup': '2-Industries',
  'FactorNum': '64',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPHARDWARE',
  'FactorDisplayName': 'ASP (JPN) Electronic Equipment and Components',
  'FactorGroup': '2-Industries',
  'FactorNum': '65',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_ENERGY',
  'FactorDisplayName': 'ASP Energy',
  'FactorGroup': '2-Industries',
  'FactorNum': '66',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPENERGY',
  'FactorDisplayName': 'ASP (JPN) Energy',
  'FactorGroup': '2-Industries',
  'FactorNum': '67',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_GOLD',
  'FactorDisplayName': 'ASP Gold',
  'FactorGroup': '2-Industries',
  'FactorNum': '68',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPHEALTH',
  'FactorDisplayName': 'ASP (JPN) Health Care',
  'FactorGroup': '2-Industries',
  'FactorNum': '69',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_HEALTH',
  'FactorDisplayName': 'ASP Health Care',
  'FactorGroup': '2-Industries',
  'FactorNum': '70',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPINDTELE',
  'FactorDisplayName': 'ASP (JPN) Industrials and Telecommunication',
  'FactorGroup': '2-Industries',
  'FactorNum': '71',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_INSURAN',
  'FactorDisplayName': 'ASP Insurance',
  'FactorGroup': '2-Industries',
  'FactorNum': '72',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_MACHINE',
  'FactorDisplayName': 'ASP Machinery',
  'FactorGroup': '2-Industries',
  'FactorNum': '73',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPMACHINE',
  'FactorDisplayName': 'ASP (JPN) Machinery',
  'FactorGroup': '2-Industries',
  'FactorNum': '74',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_MEDIARET',
  'FactorDisplayName': 'ASP Media and Retailing',
  'FactorGroup': '2-Industries',
  'FactorNum': '75',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPMEDIARET',
  'FactorDisplayName': 'ASP (JPN) Media and Retailing',
  'FactorGroup': '2-Industries',
  'FactorNum': '76',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_DIVMETAL',
  'FactorDisplayName': 'ASP Metals and Mining ex Gold and Steel',
  'FactorGroup': '2-Industries',
  'FactorNum': '77',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPMETAL',
  'FactorDisplayName': 'ASP (JPN) Metals and Mining ex Steel',
  'FactorGroup': '2-Industries',
  'FactorNum': '78',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_REALEST',
  'FactorDisplayName': 'ASP Real Estate',
  'FactorGroup': '2-Industries',
  'FactorNum': '79',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPREALEST',
  'FactorDisplayName': 'ASP (JPN) Real Estate',
  'FactorGroup': '2-Industries',
  'FactorNum': '80',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_SEMICOND',
  'FactorDisplayName': 'ASP Semiconductors and Semiconductor Equipment',
  'FactorGroup': '2-Industries',
  'FactorNum': '81',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPSEMICOND',
  'FactorDisplayName': 'ASP (JPN) Semiconductors and Semiconductor Equipme',
  'FactorGroup': '2-Industries',
  'FactorNum': '82',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_INTERNET',
  'FactorDisplayName': 'ASP Software and Services',
  'FactorGroup': '2-Industries',
  'FactorNum': '83',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPINTERNET',
  'FactorDisplayName': 'ASP (JPN) Software and Services',
  'FactorGroup': '2-Industries',
  'FactorNum': '84',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPSTEEL',
  'FactorDisplayName': 'ASP (JPN) Steel',
  'FactorGroup': '2-Industries',
  'FactorNum': '85',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_STEEL',
  'FactorDisplayName': 'ASP Steel',
  'FactorGroup': '2-Industries',
  'FactorNum': '86',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_TELECOM',
  'FactorDisplayName': 'ASP Telecommunication Services',
  'FactorGroup': '2-Industries',
  'FactorNum': '87',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_UTILITY',
  'FactorDisplayName': 'ASP Utilities',
  'FactorGroup': '2-Industries',
  'FactorNum': '88',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPUTILITY',
  'FactorDisplayName': 'ASP (JPN) Utilities',
  'FactorGroup': '2-Industries',
  'FactorNum': '89',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_AUS',
  'FactorDisplayName': 'ASP Australia Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '90',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_CHX',
  'FactorDisplayName': 'ASP China International Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '91',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_CHN',
  'FactorDisplayName': 'ASP China Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '92',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_HKG',
  'FactorDisplayName': 'ASP Hong Kong Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '93',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_IDN',
  'FactorDisplayName': 'ASP Indonesia Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '94',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPN',
  'FactorDisplayName': 'ASP Japan Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '95',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_NZL',
  'FactorDisplayName': 'ASP New Zealand Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '96',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_PAK',
  'FactorDisplayName': 'ASP Pakistan Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '97',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_PHL',
  'FactorDisplayName': 'ASP Philippines Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '98',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_SGP',
  'FactorDisplayName': 'ASP Singapore Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '99',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_KOR',
  'FactorDisplayName': 'ASP South Korea Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '100',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_LKA',
  'FactorDisplayName': 'ASP Sri Lanka Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '101',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_TWN',
  'FactorDisplayName': 'ASP Taiwan Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '102',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_THA',
  'FactorDisplayName': 'ASP Thailand Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '103',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_IND',
  'FactorDisplayName': 'ASP India Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '104',
  'StartDate': '19950131',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_MYS',
  'FactorDisplayName': 'ASP Malaysia Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '105',
  'StartDate': '19960531',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_VNM',
  'FactorDisplayName': 'ASP Vietnam Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '106',
  'StartDate': '20070731',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_BGD',
  'FactorDisplayName': 'ASP Bangladesh Mkt',
  'FactorGroup': '3-Countries',
  'FactorNum': '107',
  'StartDate': '20100531',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_AUSC',
  'FactorDisplayName': 'ASP Australia',
  'FactorGroup': '4-Currencies',
  'FactorNum': '108',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_CHNC',
  'FactorDisplayName': 'ASP China',
  'FactorGroup': '4-Currencies',
  'FactorNum': '109',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_HKGC',
  'FactorDisplayName': 'ASP Hong Kong',
  'FactorGroup': '4-Currencies',
  'FactorNum': '110',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_IDNC',
  'FactorDisplayName': 'ASP Indonesia',
  'FactorGroup': '4-Currencies',
  'FactorNum': '111',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPNC',
  'FactorDisplayName': 'ASP Japan',
  'FactorGroup': '4-Currencies',
  'FactorNum': '112',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_NZLC',
  'FactorDisplayName': 'ASP New Zealand',
  'FactorGroup': '4-Currencies',
  'FactorNum': '113',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_PAKC',
  'FactorDisplayName': 'ASP Pakistan',
  'FactorGroup': '4-Currencies',
  'FactorNum': '114',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_PHLC',
  'FactorDisplayName': 'ASP Philippines',
  'FactorGroup': '4-Currencies',
  'FactorNum': '115',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_SGPC',
  'FactorDisplayName': 'ASP Singapore',
  'FactorGroup': '4-Currencies',
  'FactorNum': '116',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_KORC',
  'FactorDisplayName': 'ASP South Korea',
  'FactorGroup': '4-Currencies',
  'FactorNum': '117',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_LKAC',
  'FactorDisplayName': 'ASP Sri Lanka',
  'FactorGroup': '4-Currencies',
  'FactorNum': '118',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_TWNC',
  'FactorDisplayName': 'ASP Taiwan',
  'FactorGroup': '4-Currencies',
  'FactorNum': '119',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_THAC',
  'FactorDisplayName': 'ASP Thailand',
  'FactorGroup': '4-Currencies',
  'FactorNum': '120',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_INDC',
  'FactorDisplayName': 'ASP India',
  'FactorGroup': '4-Currencies',
  'FactorNum': '121',
  'StartDate': '19950131',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_MYSC',
  'FactorDisplayName': 'ASP Malaysia',
  'FactorGroup': '4-Currencies',
  'FactorNum': '122',
  'StartDate': '19960531',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_VNMC',
  'FactorDisplayName': 'ASP Vietnam',
  'FactorGroup': '4-Currencies',
  'FactorNum': '123',
  'StartDate': '20070731',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_BGDC',
  'FactorDisplayName': 'ASP Bangladesh',
  'FactorGroup': '4-Currencies',
  'FactorNum': '124',
  'StartDate': '20100531',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_EMUC',
  'FactorDisplayName': 'ASP Eurozone',
  'FactorGroup': '4-Currencies',
  'FactorNum': '125',
  'StartDate': '19980930',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_CANC',
  'FactorDisplayName': 'ASP Canada',
  'FactorGroup': '4-Currencies',
  'FactorNum': '126',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_GBRC',
  'FactorDisplayName': 'ASP UK',
  'FactorGroup': '4-Currencies',
  'FactorNum': '127',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_USAC',
  'FactorDisplayName': 'ASP US',
  'FactorGroup': '4-Currencies',
  'FactorNum': '128',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_ASPEXJPN_MARKET',
  'FactorDisplayName': 'ASP Asia Pacific ex-Japan Equity',
  'FactorGroup': '5-Market',
  'FactorNum': '129',
  'StartDate': '19941230',
  'EndDate': '20751231'},
 {'Model': 'APACEFMTRD',
  'ModelVer': '100',
  'Factor': 'APACEFMTRD_JPN_MARKET',
  'FactorDisplayName': 'ASP Japan Equity',
  'FactorGroup': '5-Market',
  'FactorNum': '130',
  'StartDate': '19941230',
  'EndDate': '20751231'}]
# endregion